
# Docker-compose mis à disposition par Mickael "PAPAMICA" Asseline
# Date de mise à jour : 27/10/2020

# Variables d'environnement à déclarer :
#     - SERVICE : nom du service (exemple : plex)
#     - DATA_LOCATION : localisation des données (exemple /apps/"service")
#     - URL_LOKI : lien du serveur loki (exemple : ndd/loki/api/v1/push)
#     - NDD : lien du nom de domaine (exemple : papamica.fr)
#     - DB_USER : nom d'utilisateur pour la base de données (exemple : papamica)
#     - DB_PASSWORD : mot de passe pour la base de données
#     - SECRET_KEY : mot de passe d'accès administrateur à l'application
#     - APP_NAME : Nom de l'application

# Fonctionne avec Portainer
version: '2'
services:
  astuto-db:
    image: postgres
    container_name: $SERVICE-db
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - $DATA_LOCATION/db:/var/lib/postgresql/data
    networks:
      - proxy
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
        
  astuto:
    image: alextracy/astuto
    container_name: $SERVICE
    environment:
      - UPDATE=0
      - ENVIRONMENT=production
      - SECRET_KEY_BASE=$SECRET_KEY
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - EMAIL_CONFIRMATION=no
      - APP_NAME=$APP_NAME
      - SHOW_LOGO=no
      - POSTS_PER_PAGE=15
    volumes:
      - $DATA_LOCATION/data:/astuto
    depends_on:
      - astuto-db
    networks:
      - proxy
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=http"
      - "traefik.http.routers.$SERVICE.rule=Host(`$SERVICE.$NDD`)"
      - "traefik.http.middlewares.$SERVICE-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.$SERVICE.middlewares=$SERVICE-https-redirect"
      - "traefik.http.routers.$SERVICE-secure.entrypoints=https"
      - "traefik.http.routers.$SERVICE-secure.rule=Host(`$SERVICE.$NDD`)"
      - "traefik.http.routers.$SERVICE-secure.tls=true"
      - "traefik.http.routers.$SERVICE-secure.tls.certresolver=http"
      - "traefik.http.services.$SERVICE-secure.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"


networks:
  proxy:
    external:
      name: proxy