# Docker-compose provided by Mickael "PAPAMICA" Asseline
# Update : 10/05/2022

#& type: 3
#& title: CachetHQ
#& description: Uptime monitor alternative
#& note: Website: <a href='https://cachethq.io/' target='_blank' rel='noopener'>CachetHQ.io</a></br>Warning: Check log at the first run!
#& categories: SelfHosted, Monitoring, PAPAMICA
#& platform: linux
#& logo: http://cachethq.io/img/social/CachetFB-V.png

#% SERVICE: Name of the service (No spaces or points)
#% DATA_LOCATION: data localization (Example: /apps/service)
#% URL: Service link (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy)
#% DB_USER: Database user
#% DB_PASSWORD: Database user password
#% TIME_ZONE: Time zone (Example : Europe/Paris)

# Work with Portainer
version: "2"

services:
  postgres:
    container_name: $SERVICE-db
    image: postgres:14
    volumes:
      - $DATA_LOCATION/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
    networks:
      - default

  # CachetHQ : https://github.com/CachetHQ/Cachet
  cachet:
    image: cachethq/docker:latest
    container_name: $SERVICE
    restart: always
    links:
      - postgres:postgres
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    environment:
      - TZ=$TIME_ZONE
#      - MAIL_DRIVER=smtp
#      - MAIL_HOST=
#      - MAIL_PORT=587
#      - MAIL_USERNAME=
#      - MAIL_PASSWORD=
#      - MAIL_ADDRESS=
#      - MAIL_NAME=Notifications
#      - MAIL_ENCRYPTION=tls
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PREFIX=chq_
      - APP_KEY=
      - APP_LOG=errorlog
#      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=false
      - DEBUG=false
    depends_on:
      - postgres
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=8000"
      - "traefik.docker.network=$NETWORK"

  
networks:
  default:
    external:
      name: $NETWORK