# Docker-compose provided by Mickael "PAPAMICA" Asseline
# Update : 10/05/2022

#& type: 3
#& title: Grafana
#& description: From heatmaps to histograms, graphs to geomaps: fast and furious visualizations any way you want.
#& note: Website: <a href='https://grafana.com/grafana/dashboards/' target='_blank' rel='noopener'>Grafana.com</a>
#& categories: SelfHosted, Monitoring, PAPAMICA
#& platform: linux
#& logo: https://seeklogo.com/images/G/grafana-logo-15BA0AFA8A-seeklogo.com.png

#% SERVICE: Name of the service (No spaces or points)
#% DATA_LOCATION: Data localization (Example: /apps/service)
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy)
#% DB_USER: Database user
#% DB_PASSWORD: Database user password
#% DB_ROOT_PASSWORD: Database root password
#% KC_USER: User for Keycloak
#% KC_PASSWORD: Password for Keycloak user


# Work with Portainer

version: "2"
services:
  mariadb:
    image: mariadb:10.4.12
    container_name: $SERVICE-db
    restart: always
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    volumes:
      - $DATA_LOCATION/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD 
    labels:
      - "autoupdate=monitor"
    networks:
      - default

  keycloak:
    image: jboss/keycloak:latest
    container_name: $SERVICE
    restart: unless-stopped
    environment:
      KEYCLOAK_USER: $KC_USER
      KEYCLOAK_PASSWORD: $KC_PASSWORD
      PROXY_ADDRESS_FORWARDING: 'true'
      DB_ADDR: $SERVICE-db
      DB_DATABASE: keycloak
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    volumes:
      - /etc/localtime:/etc/localtime
    healthcheck:
      test: curl --fail http://localhost:8080/auth/realms/master
      interval: 1m
      timeout: 30s
      retries: 3
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.docker.network=$NETWORK"
    networks:
      - default
networks:
  default:
    external:
      name: $NETWORK
