# Docker-compose provided by Mickael "PAPAMICA" Asseline
# Update : 10/05/2022

#& type: 3
#& title: LogChimp
#& description: LogChimp helps you to collect, analyze, and organise your customers feedback.
#& note: Website: <a href='https://logchimp.codecarrot.net/' target='_blank' rel='noopener'>codecarrot.net</a>
#& categories: SelfHosted, PAPAMICA
#& platform: linux
#& logo: https://avatars.githubusercontent.com/u/45693574?s=200&v=4 

#% SERVICE: Name of the service (No spaces or points)
#% DATA_LOCATION: Data localization (Example: /apps/service)
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy)
#% DB_USER: Database user
#% DB_PASSWORD: Database user password
#% SECRET_KEY: App password

# Work with Portainer
version: '2'
services:
  logchimp-db:
    image: postgres:14.2
    container_name: $SERVICE-db
    environment:
      - POSTGRES_DB=logchimp
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - $DATA_LOCATION/db:/var/lib/postgresql/data
    networks:
      - default
    labels:  
    - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
        
  logchimp:
    image: philippetrounev/logchimp:latest
    container_name: $SERVICE
    environment:
      - DB_HOST=$SERVICE-db
      - DB_NAME=logchimp
      - APP_KEY=$SECRET_KEY
      - DB_USER=logchimp
      - DB_PASS=$DB_PASSWORD
#    volumes:
#      - $DATA_LOCATION/data:/astuto
    depends_on:
      - logchimp-db
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.docker.network=$NETWORK"


networks:
  default:
    external:
      name: $NETWORK