# Docker-compose mis à disposition par Mickael "PAPAMICA" Asseline
# Date de mise à jour : 27/10/2020

# Variables d'environnement à déclarer :
#     - SERVICE : nom du service (exemple : plex)

# Fonctionne avec Portainer
version: "2"

networks:
  proxy:
    external:
      name: proxy

services:
  loki:
    image: grafana/loki:1.5.0
    container_name: $SERVICE
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - proxy

  promtail:
    image: grafana/promtail:1.5.0
    container_name: $SERVICE-promtail
    restart: always
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - proxy