# Docker-compose mis à disposition par Mickael "PAPAMICA" Asseline
# Date de mise à jour : 27/10/2020

# Variables d'environnement à déclarer :
#     - SERVICE : nom du service (exemple : plex)
#     - DATA_LOCATION : localisation des données (exemple /apps/"service")
#     - URL_LOKI : lien du serveur loki (exemple : ndd/loki/api/v1/push)
#     - NDD : lien du nom de domaine (exemple : papamica.fr)
#     - DATA : localisation de vos fichiers à explorer
#     - DB_USER : nom d'utilisateur pour la base de données (exemple : papamica)
#     - DB_PASSWORD : mot de passe pour la base de données
#     - DB_ROOT : mot de passe ROOT pour la base de données

# Fonctionne avec Portainer
version: "2"
services:
  projectsend:
    image: ghcr.io/linuxserver/projectsend:latest
    container_name: $SERVICE
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - MAX_UPLOAD=<5000>
    volumes:
      - $DATA_LOCATION:/config
      - $DATA:/data
#    ports:
#      - 80:80

    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3

    
    # Facultatif  
    networks:
      - proxy
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=http"
      - "traefik.http.routers.$SERVICE.rule=Host(`$SERVICE.$NDD`)"
      - "traefik.http.middlewares.$SERVICE-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.$SERVICE.middlewares=$SERVICE-https-redirect"
      - "traefik.http.routers.$SERVICE-secure.entrypoints=https"
      - "traefik.http.routers.$SERVICE-secure.rule=Host(`$SERVICE.$NDD`)"
      - "traefik.http.routers.$SERVICE-secure.tls=true"
      - "traefik.http.routers.$SERVICE-secure.tls.certresolver=http"
      - "traefik.docker.network=proxy"

  
  # Base de donnée
  projectsend-db:
    image: mariadb:10.4.12
    container_name: $SERVICE-db
    restart: always
    volumes:
      - $DATA_LOCATION/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT
      - MYSQL_DATABASE=$SERVICE
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD

    # Facultatif  
    networks:
      - proxy
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}

networks:
  proxy:
    external:
      name: proxy