# Docker-compose provided by Mickael "PAPAMICA" Asseline
# Update : 10/05/2022

#& type: 3
#& title: Website HTML PHP 2
#& description: Simple HTML website under PHP 7.4
#& note: "<p>Website: <a href="https://github.com/LavoWeb/Docker" target="_blank" rel="noopener">Github.com</a>"
#& categories: SelfHosted, PAPAMICA
#& platform: linux
#& logo: http://assets.stickpng.com/thumbs/5847f5bdcef1014c0b5e489c.png

#% SERVICE: name of the service (no spaces or points)
#% DATA_LOCATION: data localization (example: /apps/service)
#% URL: service link (example: service.papamica.fr or service.com)
#% NETWORK: your Traefik network (example: proxy)

# Work with Portainer
version: "2"
services:
  web:
    image: lavoweb/php-7.3:latest
    container_name: $SERVICE
    volumes:
      - $DATA_LOCATION/html:/var/www/html
    restart: always
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.docker.network=$NETWORK"
networks:
  default:
    external:
      name: $NETWORK