# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-13

#& type: 3
#& title: Apprise API
#& description: Send notifications to more then 70+ services.
#& note: Website: <a href='https://github.com/caronc/apprise-api' target='_blank' rel='noopener'>Github.com</a>
#& categories: SelfHosted, PAPAMICA
#& platform: linux
#& logo: https://warehouse-camo.ingress.cmh1.psfhosted.org/a22d9206f80dfbb10748b6764fee932ff0ae1a8f/687474703a2f2f7265706f2e6e75787265662e636f6d2f7075622f696d672f6c6f676f2d617070726973652e706e67

#% SERVICE: Name of the service (No spaces or points)
#% DATA_LOCATION: Data localization (Example: /apps/service)
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy)
#% DB_USER: Database user
#% DB_PASSWORD: Database user password
#% DB_ROOT: Database root password
#% ADMIN_USER: Admin user for YourLS
#% ADMIN_PASSWORD: Admin password for YourLS

# Work with Portainer
version: "2"
services:
  apprise-api:
    image: caronc/apprise:latest
    container_name: $SERVICE
    volumes:
      - $DATA_LOCATION/config:/config
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    restart: unless-stopped
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=8000"
      - "traefik.docker.network=$NETWORK"
      
networks:
  default:
    external:
      name: $NETWORK