# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-23


#& type: 3
#& title: Dashy
#& description: Personnal dashboard
#& note: Website: <a href='https://dashy.to/' target='_blank' rel='noopener'>Dashy.to</a>
#& categories: SelfHosted, Database, PAPAMICA
#& platform: linux
#& logo: https://camo.githubusercontent.com/6c0964f4604a6807c263c83fff293258a908bdff7587910976d11c4e67a589bb/68747470733a2f2f692e6962622e636f2f796862743643592f64617368792e706e67

#% SERVICE: Name of the service (No spaces or points) [dashy]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]

# Work with Portainer
version: "3.8"
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashboard
    volumes:
      - $DATA_LOCATION/$SERVICE/conf.yml:/app/public/conf.yml
    environment:
 #     - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-secure.rule=Host(`$URL`)"
      - "traefik.http.routers.dashboard-secure.tls=true"
      - "traefik.http.routers.dashboard-secure.tls.certresolver=http"
      - "traefik.docker.network=$NETWORK"

networks:
  default:
    external:
      name: $NETWORK