# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-13

#& type: 3
#& title: Dillinger
#& description: Write your markdown with HTML live edit
#& note: Website: <a href='https://github.com/joemccann/dillinger' target='_blank' rel='noopener'>Github.com</a>
#& categories: SelfHosted, PAPAMICA
#& platform: linux
#& logo: https://d33wubrfki0l68.cloudfront.net/62334572e03c001939ed509a2a1f1009dd9bdde3/a7ee8/assets/images/tool-icons/dillinger.png

#% SERVICE: Name of the service (No spaces or points)
#% DATA_LOCATION: Data localization (Example: /apps/service)
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy)

# Work with Portainer
version: "2"
services:
  dillinger:
    image: joemccann/dillinger
    container_name: $SERVICE
    restart: always
    environment:
      - "BIND_ADDRESS=0.0.0.0"
      - "PORT=9000"
    healthcheck:
      test: wget -s 'http://localhost:9000'
      interval: 1m
      timeout: 30s
      retries: 3 
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=9000"
      - "traefik.docker.network=$NETWORK"
      
networks:
  default:
    external:
      name: $NETWORK