version: '2'

services:
  gitlab:
    image: 'polinux/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: 'git.NDD'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
    ports:
      - "8822:22"
#    volumes:
#      - '/apps/gitlab/config:/etc/gitlab'
#      - '/apps/gitlab/logs:/var/log/gitlab'
#      - '/apps/gitlab/data:/var/opt/gitlab'
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.git.entrypoints=http"
      - "traefik.http.routers.git.rule=Host(`git.NDD`)"
      - "traefik.http.middlewares.git-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.git.middlewares=git-https-redirect"
      - "traefik.http.routers.git-secure.entrypoints=https"
      - "traefik.http.routers.git-secure.rule=Host(`git.NDD`)"
      - "traefik.http.routers.git-secure.tls=true"
      - "traefik.http.routers.git-secure.tls.certresolver=http"
      - "traefik.http.services.git-secure.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"



  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
 #     - /apps/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
  
networks:
  proxy:
    external:
      name: proxy
